### ISSUE TITLE
Having issues in Firefox

### ISSUE THREAD

**Issue by warapitiya** [ds82/angular-contextmenu#5]
We are having issues in this module when it comes to Firefox. Even in your [demo link](http://ds82.github.io/angular-contextmenu/) not working on firefox. I tested it on Chrome/Safari/Firefox and Firefox is the only one i came cross this.

Even if your demo is not loading(It's giving me a console error) I manage it somehow to work in my project. But when I Right click, it popup and disappear. I tried moving my mouse over the popup while right click button press and removing after done, it doesn't disappear this time.

Please look in to this bug as this is a huge issue when it comes to firefox users.

Angular Version : 1.4.5 or 1.4.0
Angular-Contextmenu : 0.1.2

**Comment by ds82** [comment]
Thanks for bringing that up .. I'm looking into it.

**Comment by ds82** [comment]
The demo loads fine on firefox for me. I can reproduce your issue on firefox on OSX, but it works fine on windows. It think its due to this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=990614

The contextmenu triggers a click event on window/document which causes the menu to close.
I try to find a workaround for this bug ..

**Comment by ds82** [comment]
commit 8dbb2d08f7daf9a8bd35e89a7e2e992322225ac6 fixes the issue but I'm not happy with the solution. You can install this version until I found a better fix ..
